name: Discord Notifications • Merges

on:
  pull_request:
    types:
      - closed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Pull request merged
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_MERGE_URL }}
          username: 'GitHub • Merges'
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          noprefix: true
          timestamp: true
          title: '✅ Pull request merged'
          url: ${{ github.event.pull_request.html_url }}
          color: 0x57F287
          description: |
            **#${{ github.event.pull_request.number }} — ${{ github.event.pull_request.title }}**

            Merged by **${{ github.actor }}** into `${{ github.event.pull_request.base.ref }}`.

            ${{ github.event.pull_request.body && format('> {0}', replace(replace(github.event.pull_request.body, '\r', ' '), '\n', ' ')) || '' }}
          author: ${{ github.actor }}, https://github.com/${{ github.actor }}, https://github.com/${{ github.actor }}.png?size=64
          fields: |
            Repository, `${{ github.repository }}`, true
            Base ← Head, `${{ github.event.pull_request.base.ref }} ← ${{ github.event.pull_request.head.ref }}`, true
            Commits, `${{ github.event.pull_request.commits }}`, true
            Changes, `+${{ github.event.pull_request.additions }} / -${{ github.event.pull_request.deletions }} • ${{ github.event.pull_request.changed_files }} files`, true
            Author, `${{ github.event.pull_request.user.login }}`, true
            Merged by, `${{ github.actor }}`, true
            Merge SHA, `${{ github.event.pull_request.merge_commit_sha }}`, true
          footer: Merge Notifications • GitHub Actions
